version: '3.8'

services:
  app:
    build: .
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=produtos
      - DB_PORT=5432
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=produtos
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
